default:
  image: node:latest

stages:
  - build
  - deploy

build-trackit:
  stage: build
  before_script:
  - npm install -g @angular/cli
  - npm install

  script:
    - npm run build

publish-npm:
  stage: deploy
  before_script:
    - echo "@itsd_packages:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
  script:
    - npm publish
  when: manual